se-weather-app/Models/City.cs
namespace se_weather_app.Models
{
    public class City
    {
        public string? CityName { get; set; }
    }
}

se-weather-app/Models/ErrorViewModel.cs
namespace se_weather_app.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

se-weather-app/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using se_weather_app.Models;
using System.Net;
using System.Xml.Linq;


namespace se_weather_app.Controllers
{

    
    public class CityController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            var model = new City();
            return View(model);
        }

        [HttpPost]
        public IActionResult GetCity(City model)
        {
            
            return RedirectToAction(nameof(City), new { city = model.CityName });
        }


        [HttpGet("/city/{city}")]
        public async Task<IActionResult> City(string city)
        {
         
            using var client = new HttpClient();
            
            {

                try
                {

                    client.BaseAddress = new Uri("http://api.openweathermap.org");
                    var response = await client.GetAsync($"/data/2.5/weather?q={city}&appid=c26a51eff6927b6ac2a511d7799de1b7");
                    response.EnsureSuccessStatusCode();

                    var result = await response.Content.ReadAsStringAsync();
                    XNode node = JsonConvert.DeserializeXNode(result, "Root");
                    var xml = node.ToString();

                    return Ok(xml);
                }
                catch (HttpRequestException httpRequestException)
                {
                    return BadRequest($"Error: City {httpRequestException.StatusCode}");
                }
            }

        }





        }
}

se-weather-app/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using se_weather_app.Models;
using System.Diagnostics;

namespace se_weather_app.Controllers
{
    [Route("[controller]")]
    [ApiController]

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }



      


        [HttpPost]
        public ActionResult SendCity(City model)
        {
            if (ModelState.IsValid)
            {

            }
            return View();
        }





        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

se-weather-app/Views/City/City.cshtml
<>
</>

se-weather-app/Views/City/Index.cshtml
@model se_weather_app.Models.City


@{
    ViewData["Title"] = "Home Page";
    var error = ViewData["error"] as string;
}



<div class="container-fluid weather-section">
    <div class="background">
        <form method="post" asp-controller="City" asp-action="GetCity"  class="container pt-5">
  <div class="form-group">
       @if (!string.IsNullOrEmpty(error))
    {
        <div class="alert alert-danger">@error</div>
    }
    <input type="text" class="form-control" id="cityInput" placeholder="Enter city" asp-for="CityName"/>

  </div>
  <div class="text-center">
 <button type="submit" class="btn btn-primary mt-3 align-content-center">Submit</button>
  </div>
 
</form>
        
    </div>
    </div>

se-weather-app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - se_weather_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/se_weather_app.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">se_weather_app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid mainBody">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - se_weather_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>